source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '12.0'

use_frameworks!

target 'OAXCTest' do
    # 添加您的依赖库
    pod 'Alamofire'
    pod 'SwiftyJSON'
end



target 'PushActivityWidgetExtension' do
  
end
